# Generated by Django 5.0.6 on 2024-07-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('event_start_date', models.DateTimeField(verbose_name='event start date')),
                ('event_end_date', models.DateTimeField(verbose_name='event end date')),
                ('event_price', models.FloatField()),
            ],
        ),
    ]
