# Generated by Django 5.0.6 on 2024-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(verbose_name='event end date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(verbose_name='event start date'),
        ),
    ]
