# Generated by Django 5.0.6 on 2024-07-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.PositiveIntegerField(),
        ),
    ]
